services:
  db:
    image: postgres:16-alpine
    container_name: phoenix_demo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_demo_dev
    ports:
      - "53412:5432"
    volumes:
      - phoenix_demo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  phoenix_demo_data:
